version: '3.8'

services:
  pocketbase:
    build:
      context: ./pocketbase_0.28.3_linux_arm64      # 使用 arm64 版本
    container_name: pocketbase
    ports:
      - "8090:8090"
    networks:
      - app-network

  fastapi-app:
    build:
      context: ./fastapi-app     # 假设 Dockerfile 在这个目录下
    container_name: fastapi-app
    ports:
      - "6000:6000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
